[project]
name = "python-package-copier-template"
version = "0.5.0"
description = "A Copier template for modern Python projects."
readme = "README.md"
authors = [{ name = "Martín Gaitán", email = "gaitan@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "copier>=9.11.0",
    "copier-templates-extensions>=0.3.2",
    "ruff>=0.14.9",
]

[project.scripts]
python-package-copier-template = "python_package_copier_template.cli:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "python_package_copier_template"
module-root = ""

[tool.ty.src]
exclude = [".worktrees/", ".external-worktrees/"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",      # Includes Ruff's default E4, E7, and E9 rules
    "W",      # pycodestyle
    "F",      # Pyflakes and the remaining Ruff defaults
    "I",      # isort
    "C90",    # mccabe
    "A",      # flake8-builtins
    "ANN",    # flake8-annotations
    "UP",     # pyupgrade
    "RUF",    # Ruff-specific rules
    "T10",    # flake8-debugger
    "ISC",    # flake8-implicit-str-concat
    "SIM",    # flake8-simplify
    "ASYNC",  # flake8-async
    "ERA",    # eradicate
    "TRY",    # tryceratops
    "BLE",    # flake8-blind-except
    "B",      # flake8-bugbear
    "EXE",    # flake8-executable
    "FA",     # flake8-future-annotations
    "C4",     # flake8-comprehensions
    "FBT",    # flake8-boolean-trap
    "S",      # flake8-bandit
    "G",      # flake8-logging-format
    "FLY",    # flynt
    "N",      # pep8-naming
    "PIE",    # flake8-pie
    "PERF",   # Perflint
    "PL",     # Pylint
    "FURB",   # refurb
    "RET",    # flake8-return
    "TID252", # flake8-tidy-imports
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["ANN", "S101", "S108", "S603", "S607"]
"docs/conf.py" = ["A"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
docs = [
    "myst-parser>=4.0.1",
    "richterm[sphinx]>=0.2.0",
    "sphinx>=8.2.3",
    "sphinx-book-theme>=1.1.4",
    "sphinxcontrib-mermaid>=1.0.0",
]
qa = [
    "ty>=0.0.27",
]
